### ISSUE TITLE
Content inside tasks and notes is overwritten permanently

### ISSUE THREAD

**Issue by khushnoodasif** [thesamim/TickTickSync#10]
Currently you can sync and create tasks from ticktick but you cant add content to these tasks and all content which are synced to Obsidian become overwritten and theres no way to get it back as there are not deleted but overwritten.

**Comment by mitul45** [comment]
Exactly the same thing happened to me!

I put a lot of description in TickTick tasks and now all of them are gone 😞 

The worst thing is, the JSON created as a backup is not valid according to TickTick, I tried to import it from "settings" but it only restored the lists, not the actual tasks.

I think you should advise people to create backup on TickTick before giving this plugin a try.

**Comment by thesamim** [comment]
> The worst thing is, the JSON created as a backup is not valid

If it is worth your time:

1. Create a CSV backup from TickTick
2. Compare the task contents from the JSON back up to the CSV created
3. Transfer the contents to the CSV file from the JSON file
4. Import the CSV file.

**Comment by thesamim** [comment]
@mitul45 : [Issue](https://github.com/thesamim/TickTickSync/issues/14) opened to address the backup format

**Comment by mitul45** [comment]
@thesamim I actually ended up creating a small script that does exactly that, maybe you can use that: https://gist.github.com/mitul45/5028226c709f2c6e555c40b28acdd565.

**Comment by thesamim** [comment]
Thanks @mitul45 , will use as a starting point when I get to it.

**Comment by denizido** [comment]
Are there plans to sync the descriptions in some way? 

I wish I could edit a note/task in ticktick and it would sync with a note in obsidian and vice versa.

Or maybe just a setting for the user to have the option to not erase all the task descriptions?

**Comment by thesamim** [comment]
> Or maybe just a setting for the user to have the option to not erase all the task descriptions?

Not erasing Task Description is going to be in the next release. Also in the next release: Items will be bi-directionally synced.

> I wish I could edit a note/task in ticktick and it would sync with a note in obsidian and vice versa.
I'm open to suggestions as to how to handle that. 

This is one example of handling:
```
- [ ] this is a task [link](https://ticktick.com/webapp/#q/all/tasks/6587149d71f5b191a041b685) #ticktick  %%[ticktick_id:: 6587149d71f5b191a041b685]%%
      This is one option of handling all the notes in the description.
      
      But note that this will make tasks very mess.
```

What else would you like to see?

**Comment by denizido** [comment]
I actually have a suggestion, thought I don't know if it would be feasable.

My idea would be adding a link to another note, that has the contents/description of the tasks and - maybe in the future - its properties.

I don't that this would be necessary for all tasks, but just specific ones; maybe the ones with a particular tag.

So the main page may look something like this:

```
- [ ] task one [link-to-task-one](linktotaskone) [link](https://ticktick.com/webapp/#q/all/tasks/65871648ce4db23f7404098a) #ticktick  %%[ticktick_id:: 65871648ce4db23f7404098a]%%
```

The task page, something like this:


**task one**
```
---
task_id: xxxxxx
project_id: yyyyy
due_date: 2024-01-01
completed: false
etc...
---


Task content/description.

```

**Comment by raykr** [comment]
```
- [ ] this is a task [link](https://ticktick.com/webapp/#q/all/tasks/6587149d71f5b191a041b685) #ticktick  %%[ticktick_id:: 6587149d71f5b191a041b685]%%
      This is one option of handling all the notes in the description.
      
      But note that this will make tasks very messy.
```
@quanru I love this scheme so much! Is it already supported? It's not work till now when I test in v1.0.32.

**Comment by thesamim** [comment]
> @thesamim I love this scheme so much! Is it already supported? It's not work till now when I test in v1.0.32.

Not yet. It's on the roadmap...
